--- /usr/src/sys/Makefile.orig	2018-10-18 17:24:13.181298000 +0200
+++ /usr/src/sys/Makefile	2018-10-18 17:24:34.957500000 +0200
@@ -2,7 +2,7 @@
 
 # Directories to include in cscope name file and TAGS.
 CSCOPEDIRS=	bsm cam cddl compat conf contrib crypto ddb dev fs gdb \
-		geom gnu isa kern libkern modules net net80211 \
+		geom gnu isa kern libkern modules net net80211 netcan \
 		netgraph netinet netinet6 netipsec netnatm netpfil \
 		netsmb nfs nfsclient nfsserver nlm ofed opencrypto \
 		rpc security sys ufs vm xdr xen ${CSCOPE_ARCHDIR}
